//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSTOK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLKATEGORİLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLKATEGORİLER()
        {
            this.TBLURUNLER = new HashSet<TBLURUNLER>();
        }
    
        public short KategoriId { get; set; }
        [Required(ErrorMessage="Kategori Adı Giriniz!")]//bak bununla beraber artık kullanıcı kategorş ad a boş değer göndermke istediğinde önlyecek ve hata verecek 
        //ama bu hata beni sadece 404 sayfasına atar ,kullanıcıya haber vermem için cotroller ve yenikategoride tanımlamalara deam etmem lazım
        public string KategoriAd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLURUNLER> TBLURUNLER { get; set; }
    }
}
